// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_middleware.tsx";
import * as $2 from "./routes/api/favorite.ts";
import * as $3 from "./routes/api/get-tweet-info.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/api/login.ts";
import * as $6 from "./routes/api/logout.ts";
import * as $7 from "./routes/api/signup.ts";
import * as $8 from "./routes/explore.tsx";
import * as $9 from "./routes/favorites.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/login.tsx";
import * as $12 from "./routes/signup.tsx";
import * as $$0 from "./islands/BottomBar.tsx";
import * as $$1 from "./islands/ExploreLayout.tsx";
import * as $$2 from "./islands/FavoriteLayout.tsx";
import * as $$3 from "./islands/HomeLayout.tsx";
import * as $$4 from "./islands/Input.tsx";
import * as $$5 from "./islands/LoginComponent.tsx";
import * as $$6 from "./islands/Navbar.tsx";
import * as $$7 from "./islands/SignUpComponent.tsx";
import * as $$8 from "./islands/TweetContainer.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_middleware.tsx": $1,
    "./routes/api/favorite.ts": $2,
    "./routes/api/get-tweet-info.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/api/login.ts": $5,
    "./routes/api/logout.ts": $6,
    "./routes/api/signup.ts": $7,
    "./routes/explore.tsx": $8,
    "./routes/favorites.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/login.tsx": $11,
    "./routes/signup.tsx": $12,
  },
  islands: {
    "./islands/BottomBar.tsx": $$0,
    "./islands/ExploreLayout.tsx": $$1,
    "./islands/FavoriteLayout.tsx": $$2,
    "./islands/HomeLayout.tsx": $$3,
    "./islands/Input.tsx": $$4,
    "./islands/LoginComponent.tsx": $$5,
    "./islands/Navbar.tsx": $$6,
    "./islands/SignUpComponent.tsx": $$7,
    "./islands/TweetContainer.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
